language: rust
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
install:
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.5.tar.gz
    - tar -xzvf SDL2-2.0.5.tar.gz
    - cd SDL2-2.0.5
    - ./configure
    - make
    - sudo make install
    - cd -
rust:
  - stable
  - beta
  - nightly
