language: rust
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev

install:
  - ci/install.sh

build:
  - ci/build.sh

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - TARGET=native
    - TARGET=web
