language: rust
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev

services:
  - docker

install:
  - ci/install.sh

script:
  - ci/script.sh

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - DOCKER_IMAGE=rust-emsdk
  matrix:
    - TARGET=native
    - TARGET=web
