[package]
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
name = "game-of-life-rs"
version = "0.1.0"

[dependencies]
board-game-geom = "0.2.0"
gfx = "0.12.1"
gfx_core = "0.4.0"
gfx_device_gl = "0.11.2"
image = "0.10.3"
piston = "0.26.0"
piston2d-gfx_graphics = "0.32.0"
piston2d-graphics = "0.18.0"
pistoncore-sdl2_window = "0.36.0"
rand = "0.3.14"
shader_version = "0.2.1"
time = "0.1.35"
