[package]
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
name = "game-of-life-rs"
version = "0.1.0"

[dependencies]
board-game-geom = "0.2.0"
gfx = "0.12.1"
gfx_core = "0.4.0"
image = "0.10.3"
lazy_static = "0.2.1"
libc = "0.2.17"
piston = "0.26.0"
piston2d-graphics = "0.18.0"
piston2d-opengl_graphics = "0.35.0"
pistoncore-sdl2_window = "0.36.0"
rand = "0.3.14"
shader_version = "0.2.1"
time = "0.1.35"

[replace]

[replace."num_cpus:1.1.0"]
git = "https://github.com/seanmonstar/num_cpus"

[replace."piston-shaders_graphics2d:0.1.0"]
path = "../emscripten/shaders/graphics2d"

[replace."piston2d-opengl_graphics:0.35.0"]
path = "../emscripten/opengl_graphics"
