[package]

name = "spinning-square"
version = "0.1.0"
authors = [
    "TyOverby <ty@pre-alpha.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.33.0"
piston2d-graphics = "0.21.1"
pistoncore-sdl2_window = "0.44"
piston2d-opengl_graphics = "0.46.0"
